### ISSUE TITLE
Initial project plan

### ISSUE THREAD

**Issue by SSM121** [SSM121/2ndPlaceBestPlace#1]
- [ ] A summary of the project being built
- [ ] A description of team organization,
- [ ] A description of the overall software development process (provided by the instructor)
- [ ] Policies, procedures, or tools for communication, including plans for team meetings, online-coordination, reporting, etc.
- [ ] Risk analysis
- [ ] reference to the README.md for the configuration management plan
